# Mengenal Konsep Variabel & Assignment

## Data Numeric

In [12]:
#Trial Case 
tinggi_badan = 190
tinggiBadan = 180
Tinggibadan = 185

In [13]:
Tinggibadan

185

In [1]:
tinggi_badan = 173

berapa isi dari variabel tinggi_badan sekarang?

In [2]:
tinggi_badan

173

ganti nilai tinggi_badan dengan 170

In [3]:
tinggi_badan = 170

berapa isi dari variabel tinggi_badan sekarang?

In [4]:
tinggi_badan

170

In [5]:
tinggi_badan/100

1.7

In [6]:
tinggi_badan_in_m = tinggi_badan/100
tinggi_badan_in_m

1.7

## Data String

In [7]:
nama_depan = 'Raffi'
nama_belakang = 'Ahmad'

In [8]:
nama_depan+nama_belakang

'RaffiAhmad'

In [9]:
nama_depan+" "+nama_belakang

'Raffi Ahmad'

## [CHALLENGE] Membuat variabel baru

In [10]:
#new variable
name = 'Ciaa'
age = 19

In [11]:
"Halo, my name is "+name+". Iam "+str(age)+" years old"

'Halo, my name is Ciaa. Iam 19 years old'

# Import Pandas Library

In [14]:
#memanggil library pandas
import pandas as pd

# Membaca Dataset

In [23]:
cia_dataset = pd.read_csv('rakamin_class.csv')

In [24]:
cia_dataset

,registration_id,name,email,phone,age,city,province,active,class,score
0,RK20202344,Nina,nina@gmail.com,628198157,57,Tanjungpinang,Kepulauan Riau,1,6,80
1,RK20202345,Dyah,dyah@gmail.com,628306496,24,Bogor,Jawa Barat,0,2,66
2,RK20202346,Prima,prima@ymail.com,628755450,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,55
3,RK20202347,Firman,firman@google.com,628638112,59,Metro,Lampung,1,6,93
4,RK20202348,Eva,eva@rakamin.com,628702735,42,Malang,Jawa Timur,0,5,80
...,...,...,...,...,...,...,...,...,...,...
95,RK20202439,Abdul,abdul@gmail.com,628989064,54,Samarinda,Kalimantan Timur,0,6,59
96,RK20202440,Ria,ria@gmail.com,628535849,56,Batam,Kepulauan Riau,0,6,58
97,RK20202441,Putra,putra@gmail.com,628205046,51,Palangkaraya,Kalimantan Tengah,1,6,71
98,RK20202442,Kokom,kokom@facebook.com,628718477,23,Bekasi,Jawa Barat,0,2,73
99,RK20202443,Ilham,ilham@gmail.com,628680755,29,Tasikmalaya,Jawa Barat,1,2,52

# Operasi Sederhana Data Frame

## a. shape

Melihat ukuran Data Frame (baris & kolom)

In [25]:
#melihat dimensi kebawah / row dan kesamping / kolom
#indeks dari 0
cia_dataset.shape

(100, 10)

In [26]:
cia_dataset.shape[0]

100

In [27]:
cia_dataset.shape[1]

10

## b. columns

Melihat semua nama kolom

In [28]:
cia_dataset.columns

Index(['registration_id', 'name', 'email', 'phone', 'age', 'city', 'province',
       'active', 'class', 'score'],
      dtype='object')

## c. head()

Melihat N baris pertama  (default N=5)

In [29]:
cia_dataset.head()

,registration_id,name,email,phone,age,city,province,active,class,score
0,RK20202344,Nina,nina@gmail.com,628198157,57,Tanjungpinang,Kepulauan Riau,1,6,80
1,RK20202345,Dyah,dyah@gmail.com,628306496,24,Bogor,Jawa Barat,0,2,66
2,RK20202346,Prima,prima@ymail.com,628755450,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,55
3,RK20202347,Firman,firman@google.com,628638112,59,Metro,Lampung,1,6,93
4,RK20202348,Eva,eva@rakamin.com,628702735,42,Malang,Jawa Timur,0,5,80

In [30]:
cia_dataset.head(3)

,registration_id,name,email,phone,age,city,province,active,class,score
0,RK20202344,Nina,nina@gmail.com,628198157,57,Tanjungpinang,Kepulauan Riau,1,6,80
1,RK20202345,Dyah,dyah@gmail.com,628306496,24,Bogor,Jawa Barat,0,2,66
2,RK20202346,Prima,prima@ymail.com,628755450,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,55

## d. tail()

Melihat N baris terakhir (default N=5)

In [31]:
cia_dataset.tail()

,registration_id,name,email,phone,age,city,province,active,class,score
95,RK20202439,Abdul,abdul@gmail.com,628989064,54,Samarinda,Kalimantan Timur,0,6,59
96,RK20202440,Ria,ria@gmail.com,628535849,56,Batam,Kepulauan Riau,0,6,58
97,RK20202441,Putra,putra@gmail.com,628205046,51,Palangkaraya,Kalimantan Tengah,1,6,71
98,RK20202442,Kokom,kokom@facebook.com,628718477,23,Bekasi,Jawa Barat,0,2,73
99,RK20202443,Ilham,ilham@gmail.com,628680755,29,Tasikmalaya,Jawa Barat,1,2,52

In [32]:
cia_dataset.tail(3)

,registration_id,name,email,phone,age,city,province,active,class,score
97,RK20202441,Putra,putra@gmail.com,628205046,51,Palangkaraya,Kalimantan Tengah,1,6,71
98,RK20202442,Kokom,kokom@facebook.com,628718477,23,Bekasi,Jawa Barat,0,2,73
99,RK20202443,Ilham,ilham@gmail.com,628680755,29,Tasikmalaya,Jawa Barat,1,2,52

# Data Sorting

In [33]:
cia_dataset.head()

,registration_id,name,email,phone,age,city,province,active,class,score
0,RK20202344,Nina,nina@gmail.com,628198157,57,Tanjungpinang,Kepulauan Riau,1,6,80
1,RK20202345,Dyah,dyah@gmail.com,628306496,24,Bogor,Jawa Barat,0,2,66
2,RK20202346,Prima,prima@ymail.com,628755450,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,55
3,RK20202347,Firman,firman@google.com,628638112,59,Metro,Lampung,1,6,93
4,RK20202348,Eva,eva@rakamin.com,628702735,42,Malang,Jawa Timur,0,5,80

### Mengurutkan age dari termuda ke tertua (ASCENDING - Kecil ke besar)

In [34]:
cia_dataset.sort_values('age')

,registration_id,name,email,phone,age,city,province,active,class,score
92,RK20202436,Munaroh,munaroh@hotmail.com,628636716,15,Kota Administrasi Jakarta Barat,Jakarta,0,1,91
82,RK20202426,Een,een@facebook.com,628018377,15,Kota Administrasi Jakarta Barat,Jakarta,1,1,74
2,RK20202346,Prima,prima@ymail.com,628755450,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,55
5,RK20202349,Bagus,bagus@hotmail.com,628816223,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,84
7,RK20202351,Yuni,yuni@google.com,628714465,16,Kota Administrasi Jakarta Pusat,Jakarta,0,1,87
...,...,...,...,...,...,...,...,...,...,...
0,RK20202344,Nina,nina@gmail.com,628198157,57,Tanjungpinang,Kepulauan Riau,1,6,80
42,RK20202386,Hendra,hendra@hotmail.com,628452630,58,Bandar Lampung,Lampung,1,6,75
32,RK20202376,Hafizh,hafizh@google.com,628535862,58,Bandar Lampung,Lampung,1,6,82
3,RK20202347,Firman,firman@google.com,628638112,59,Metro,Lampung,1,6,93
13,RK20202357,Amelia,amelia@ymail.com,628375103,59,Metro,Lampung,1,6,67

In [35]:
cia_dataset.sort_values('age', ascending=True)

,registration_id,name,email,phone,age,city,province,active,class,score
92,RK20202436,Munaroh,munaroh@hotmail.com,628636716,15,Kota Administrasi Jakarta Barat,Jakarta,0,1,91
82,RK20202426,Een,een@facebook.com,628018377,15,Kota Administrasi Jakarta Barat,Jakarta,1,1,74
2,RK20202346,Prima,prima@ymail.com,628755450,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,55
5,RK20202349,Bagus,bagus@hotmail.com,628816223,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,84
7,RK20202351,Yuni,yuni@google.com,628714465,16,Kota Administrasi Jakarta Pusat,Jakarta,0,1,87
...,...,...,...,...,...,...,...,...,...,...
0,RK20202344,Nina,nina@gmail.com,628198157,57,Tanjungpinang,Kepulauan Riau,1,6,80
42,RK20202386,Hendra,hendra@hotmail.com,628452630,58,Bandar Lampung,Lampung,1,6,75
32,RK20202376,Hafizh,hafizh@google.com,628535862,58,Bandar Lampung,Lampung,1,6,82
3,RK20202347,Firman,firman@google.com,628638112,59,Metro,Lampung,1,6,93
13,RK20202357,Amelia,amelia@ymail.com,628375103,59,Metro,Lampung,1,6,67

### Mengurutkan age dari tertua ke termuda (DESCENDING - Besar ke Kecil)

In [37]:
cia_dataset.sort_values(['age', 'name'], ascending=[True,False])

,registration_id,name,email,phone,age,city,province,active,class,score
92,RK20202436,Munaroh,munaroh@hotmail.com,628636716,15,Kota Administrasi Jakarta Barat,Jakarta,0,1,91
82,RK20202426,Een,een@facebook.com,628018377,15,Kota Administrasi Jakarta Barat,Jakarta,1,1,74
7,RK20202351,Yuni,yuni@google.com,628714465,16,Kota Administrasi Jakarta Pusat,Jakarta,0,1,87
2,RK20202346,Prima,prima@ymail.com,628755450,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,55
5,RK20202349,Bagus,bagus@hotmail.com,628816223,16,Kota Administrasi Jakarta Pusat,Jakarta,1,1,84
...,...,...,...,...,...,...,...,...,...,...
47,RK20202391,Budi,budi@gmail.com,628823013,57,Tanjungpinang,Kepulauan Riau,1,6,70
42,RK20202386,Hendra,hendra@hotmail.com,628452630,58,Bandar Lampung,Lampung,1,6,75
32,RK20202376,Hafizh,hafizh@google.com,628535862,58,Bandar Lampung,Lampung,1,6,82
3,RK20202347,Firman,firman@google.com,628638112,59,Metro,Lampung,1,6,93
13,RK20202357,Amelia,amelia@ymail.com,628375103,59,Metro,Lampung,1,6,67

### Ambil data 10 orang pertama sesuai abjad

### [CHALLENGE] Ambil data 10 orang dengan score terendah

# Data Filtering

### Filter kolom name, email, phone, province

In [ ]:
cia_dataset[ ['name','email','phone','province'] ].head()

## Ambil nama tiap orang beserta score nya

In [ ]:
cia_dataset[['name','score']]

### Ambil data orang-orang dari Jakarta

In [ ]:
cia_dataset[cia_dataset['province']=='Jakarta']

### Ambil data orang-orang yang berusia lebih dari 30 tahun

In [ ]:
cia_dataset[cia_dataset['age'] > 30]

### Ambil data orang-orang dengan score <= 60

In [ ]:
cia_dataset[cia_dataset['score'] <= 60]

## Ada berapa orang yang punya score <= 60

### Ambil data orang-orang yang bukan dari kota Depok

In [ ]:
cia_dataset[cia_dataset['city'] != 'Depok']

## Ambil data orang-orang dari Jawa Timur dengan umur > 40

In [ ]:
cia_dataset[ (cia_dataset['province'] == 'Jawa Timur') & (cia_dataset['age'] > 40) ]

## Ambil data orang-orang yang dari Surabaya, atau punya score > 90

In [ ]:
cia_dataset[ (cia_dataset['city'] == 'Surabaya') | (cia_dataset['score'] > 90) ]

## Ambil data orang-orang yang bukan dari Malang

## Siapa orang paling tua yang berasal dari Jawa Tengah?

## [CHALLENGE] Ada berapa banyak orang di kelas 4 yang berasal dari Jawa Tengah?

## [CHALLENGE] Siapa nama pemilik no HP 628833542?

## Untuk semua orang di kelas 1, tunjukkan info nama, kota, dan provinsi nya

# Data Aggregation

## Melihat jumlah orang per provinsi

In [ ]:
cia_dataset.groupby('province')['registration_id'].count()

Tambahkan .reset_index() untuk membuat dataframe yang kolomnya rata

## Melihat rata-rata score tiap kelas

In [ ]:
cia_dataset.groupby('class')['score'].mean().reset_index()

diurutkan dari rata-rata score tertinggi

In [ ]:
cia_dataset.groupby('class')['score'].mean().reset_index().sort_values('score',ascending=False)

## Untuk orang-orang dari Jakarta, berapa rata-rata score per kota?

## Berapa banyak orang yang aktif, dan tidak aktif?